[package]
name = "concurrentes-proyecto-2"
version = "0.1.0"
authors = ["FMAA1997 <fede.alvarez1997@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.8.2"
uuid = { version = "0.8", features = ["v4"] }
csv = "1.1.5"
rand = "0.8.3"